name: Generate Courses JSON


# 允许 GitHub Actions 修改仓库
permissions:

  contents: write



on:

  # 手动运行

  workflow_dispatch:



  # 修改 Excel 后自动运行

  push:

    paths:

      - "data/course_manage.xlsx"




jobs:


  generate-json:


    runs-on: ubuntu-latest



    steps:



      # 拉取代码

      - name: Checkout repository

        uses: actions/checkout@v4

        with:

          token: ${{ secrets.GITHUB_TOKEN }}





      # 安装 Python

      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"





      # 安装 Excel 读取库

      - name: Install dependencies

        run: |

          pip install openpyxl





      # 执行生成脚本

      - name: Generate JSON

        run: |

          python scripts/generate_json.py





      # 提交生成结果

      - name: Commit generated JSON

        run: |


          git config --global user.name "github-actions"

          git config --global user.email "actions@github.com"



          git add data/courses



          git commit -m "Auto generate course json" || echo "No changes"



          git push origin HEAD:${{ github.ref }}
