name: Generate Courses JSON


permissions:

  contents: write



on:


  workflow_dispatch:



  push:

    paths:

      - "data/course_manage.xlsx"

      - "data/videos.json"




jobs:


  generate-json:


    runs-on: ubuntu-latest



    steps:



      - name: Checkout repository

        uses: actions/checkout@v4

        with:

          token: ${{ secrets.GITHUB_TOKEN }}





      - name: Setup Python

        uses: actions/setup-python@v5

        with:

          python-version: "3.11"





      - name: Install dependencies

        run: |

          pip install openpyxl





      - name: Generate JSON

        run: |

          python scripts/generate_json.py





      - name: Commit generated JSON

        run: |


          git config --global user.name "github-actions"


          git config --global user.email "actions@github.com"



          git add data/courses



          git commit -m "Auto generate course json" || echo "No changes"



          git push origin HEAD:${{ github.ref }}
